# backend/app/services/ai_enrichment.py
"""Placeholder for the Claude-backed AI explainability layer.

The real enrichment layer (subgraph summary -> Claude -> structured
explanation for low-confidence cases) is not built yet — see the AI
enrichment section of CLAUDE.md. This stub keeps the ``/enrich`` endpoint
and its response contract alive so the frontend degrades gracefully; it
returns an honest "not yet available" report rather than a fabricated
risk assessment.
"""

from typing import Dict, Any


class AIEnrichmentService:
    @staticmethod
    async def generate_explanation(account_id: str) -> Dict[str, Any]:
        return {
            "account_id": account_id,
            "risk_level": "unknown",
            "confidence": 0.0,
            "explanation": (
                "AI enrichment is not yet implemented. This endpoint is a "
                "placeholder; natural-language risk explanations will be "
                "generated by the Claude enrichment layer once it is wired in. "
                "Use the GNN risk classifier and graph detectors for scoring."
            ),
            "detected_typology": None,
            "compliance_summary": (
                "Automated AI explanation unavailable — manual review required."
            ),
        }
